language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

matrix:
  include:
    - os: linux
      env: TASK=regular
    - os: linux
      env: TASK=mpi
    - os: linux
      env: TASK=gpu
    - os: linux
      env: TASK=pip
    - os: linux
      env: TASK=pylint
    - os: linux
      env: TASK=if-else
    - os: osx
      env: TASK=regular
    - os: osx
      env: TASK=mpi
    - os: osx
      env: TASK=pip

before_install:
- test -n $CC  && unset CC
- test -n $CXX && unset CXX

install:
- bash .travis/setup.sh
- bash conda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda

script:
- bash .travis/test.sh

notifications:
  email: false

deploy:
  provider: releases
  api-key:
    secure: "KotGjHZeeiUoRL6bQ38BFiPS6vsw1EWHiEZU3gRz5FZ4YZpFKx+O6oez9NPGedfA8eXpL0b/WvzpGOneohG+0gBksWTK2quccBB19LmlNiV7hcGgzfa10tIwibqOiNLFeTOhD+/M80V0KOTAztHRGG6Oz2JJ0WjtziU4W26q8pA2z6CGBibvDjnTnCZAHWdzwCP84uUAw9/+O59/i8kZ290+/JqbrdprdPVt/Q8oo8DbuqWPGM/8SMeqBzZE8lCDqWPAfT2qh/cr+cjR0td7iAXspEPjNv2Ca0hHj5h1VjzHvGmPQaETuZwxsDXJT4G4fud5lWHBzVXdgbC5E90Srn8VcqS8iVp4HqpfIXzLYjODpqdc8issxd0ODK9R2O3lIq6P/Z9W4yZI8XWWbB9vTQ4X18ghvabJxEVMtOP+DOuOzIfzrM6ml4JeXoM+byYGB5gdoGCiYtxlYNPDJL7avckYq1Ed0SmZgcwlt/AG5wtoge8ieBvm7TCFEqJ7RQFhLt5tiulg6cAKo/xTa5Q5T5I7GefiqGYK469Ns6+aB+WKq79J06S7GkBhsD+KElAf3LQ1jSPumSCztalmq0f1jr1UIS2dqwES47/neHBrbgiLBYqY9gTHyi5faz2g/eDLYiOrCGMB/0EyCmcKrt+TP9y+g9ZjUHA8sNu1QlcHJIE="
  file_glob: true
  file: python-package/dist/*.whl
  skip_cleanup: true
  on:
    condition: "$TASK = pip"
    tags: true
    all_branches: true
