language: cpp
sudo: required
dist: trusty

compiler:
  - gcc

matrix:
  include:
    - os: linux
      env: TASK=regular
    - os: linux
      env: TASK=mpi
    - os: linux
      env: TASK=gpu
    - os: linux
      env: TASK=pip
    - os: linux
      env: TASK=pylint
    - os: linux
      env: TASK=if-else
    - os: osx
      env: TASK=regular
    - os: osx
      env: TASK=mpi
    - os: osx
      env: TASK=pip

before_install:
- test -n $CC  && unset CC
- test -n $CXX && unset CXX

install:
- bash .travis/setup.sh
- bash conda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda

script:
- bash .travis/test.sh

notifications:
  email: false

deploy:
  provider: releases
  api-key:
    secure: "qQCKD35x3z9ZelsZxKukQZ45H2x6BfsIajJFoqP3+I3qEFI2x9NnSMxp/CwfG6rj0icK67fHFGpvf/5Fddw63oxqhhAlT9Vs280rDn0b+KN+Y+3UpCrjEp+AikQXTOYcdaERntmPOb/+PZiTyWYI1d5EYPChB0si/NAKEqYwHbjpEaZb+y6DaePIotOdVKKCVGB4Vp7Ui+uiyONs9xbG1J/eh+kxkZ44y0IbaWxH5YGAAlwOYriyy2mmIw3XiCGrPNT74of2en6/OTKzXlqm2ApcfD0/SQ0DhW3vEqvJj3qK2ytRjXEGBNFnACKIf6gToIMcG0rFW1rkrzTmTdsMGrxmb3OFT+1RXLrGKGA2XyGhE7Mj5uW+WknfNHCR4x4nMCQ7sneBED9vRt/aafr+BvCFN8rkzHjrbL42Q/nMggteIQcFQHzVsKqJ0ItMWlhQ5pMN2DZfFT7OTxbzcc/GVnKgbR2ap3OaRnuQs1ZNjn+Oq9eP6nTMIEXSCSvHLM65Bu0NikqFpMR5l03/W4OZN6JyEXS0Y0MlMNTaRUANNG47QBeFR/X7jodYA3WeqBU0JMU9xpvoWDR7/sUaP2PpLs49mMsenTL/dLcXSi55kHRrmUlazaQinSnP6V7gjMmfdYo6UqdiyAJKwHbdHJ+0VwWfzoPg470yLtVZcKAfXXc="
  file_glob: true
  file: python-package/dist/*.whl
  skip_cleanup: true
  on:
    condition: "$TASK = pip"
    tags: true
    all_branches: true
